### ISSUE TITLE
Update MercadoPago Android SDK

### ISSUE THREAD

**Issue by franblanco95** [BlackBoxVision/react-native-mercadopago-px#67]
**Describe the bug**

Hello guys, I'm having a problem when uploading my application to the playstore..

It says that the app contains the SDK com.mercadopago.android.px:services 4.45.0, which does not comply with the new PlayStore policies on data security.

That's why they ask to update the SDK to 4.53.2. There is time until October 25, otherwise we must uninstall the application library, because the updates will be rejected.

**Screenshots**

![image](https://user-images.githubusercontent.com/83734276/188480386-7c7804b0-4156-4366-add6-0510b52b851c.png)

**Comment by checomendoza** [comment]
i am facing with the same problem. I have updated the skd version in the package.json file (line 145) to version 4.53.2 but Android Studio cannot resolve com.mercadopago.android.px:checkout:4.53.2
Seeing the documentation of the px-android repo of mercadopago, they have moved the latest version to a new repository
```
repositories {
     ...
     maven {
         url 'https://artifacts.mercadolibre.com/repository/android-releases/'
     }
}
```
I have changed and updated as indicated there and I was able to compile with version 4.53.2, but when I upload the update to the Play Store it keeps rejecting me for the same reason
<img width="1095" alt="Screen Shot 2022-09-05 at 13 53 42" src="https://user-images.githubusercontent.com/5015954/188492019-ed479cf7-0379-4669-b23c-228be7f7dfea.png">

**Comment by checomendoza** [comment]
Hi guys! I've found a little solution for this issue. I have add mave url that specifies by mercadolibre, inside build.gradle from android folder of the project.
Thats work for me.

**Comment by JonatanSalas** [comment]
Hi @checomendoza would you mind to make a PR with your solution? We can merge it and make a release.

**Comment by JonatanSalas** [comment]
We've published `v0.8.0`, so you can fix the upgrade issue by installing the newer version doing:

```bash
npm i @blackbox-vision/react-native-mercadopago-px@0.8.0
```

**Comment by Marcoo09** [comment]
Hi guys, I hope you're doing well
I'm on the last version but I still have the problem:
<img width="712" alt="image" src="https://user-images.githubusercontent.com/18408823/189463216-dcf56c61-fabf-4784-a855-4c74334df2b4.png">

**Comment by franblanco95** [comment]
> Hi guys, I hope you're doing well I'm on the last version but I still have the problem: <img alt="image" width="712" src="https://user-images.githubusercontent.com/18408823/189463216-dcf56c61-fabf-4784-a855-4c74334df2b4.png">

same problem here..

**Comment by JonatanSalas** [comment]
If you want, you can make a PR if you find how to patch the issue. Currently with our team we're reaching a big milestone with a client so we aren't going to have enough time to work on this. 

If this issue is really blocking for you, you can reach us to hello@blackbox-vision.tech and we can offer paid consulting  hours.

**Comment by Marcoo09** [comment]
I make it work doing a couple of changes, on the package I need to change the kotlin version to >=1.5.0
I tried with 1.7.10:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/18408823/190926301-8d1e3b46-3ec2-478f-98e8-03721c81d992.png">
Then on android/build.gradle of the app I need to add:
<img width="733" alt="image" src="https://user-images.githubusercontent.com/18408823/190926334-abf67bd2-233a-4ea8-bef6-6c22a2d0a9a7.png">
I don't know why I need to do the latter, in the build.gradle of the library there is already this same thing

**Comment by franblanco95** [comment]
Hello guys, the workaround that @Marcoo09 shares works okey. 

When you add the maven url on android>build.gradle and build, android studio says that the kotlin version of the library has to be changed... So updating it will fix the problem! Thank you marco

**Comment by juliscotto** [comment]
Hi! Im still getting the same error in playstore, even after doing all of the above. How can I fix this?
